### ISSUE TITLE
Show Correct Display Values for Map Selection Results

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm-web#10]
Values for lookup and foreign key columns in the map selection results table should correspond to the correct display values.

![image](https://user-images.githubusercontent.com/3840267/108091561-e2ef5480-708c-11eb-9cd7-e20bed262d0f.png)

**Comment by wanjohikibui** [comment]
Resolved
![image](https://user-images.githubusercontent.com/4972951/109137144-f031d080-7769-11eb-930e-8bde6c264637.png)

**Comment by gkahiu** [comment]
This is resolved, thanks.
