### ISSUE TITLE
Clear Map Selection

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm-web#11]
Can we have a button for clearing map selection (and results) just below the ones for selecting spatial units by polygon and rectangle?

![image](https://user-images.githubusercontent.com/3840267/108092042-5a24e880-708d-11eb-80df-e1a5d30176a7.png)

**Comment by wanjohikibui** [comment]
I have added a button to clear the selection results, both on the map and the table. 
![image](https://user-images.githubusercontent.com/4972951/109135345-0343a100-7768-11eb-9b41-14dc3a213ba6.png)

**Comment by gkahiu** [comment]
The clear selection is still missing, see below.

![image](https://user-images.githubusercontent.com/3840267/115863512-38a1fd80-a43e-11eb-9cee-702c34d41659.png)

**Comment by gkahiu** [comment]
The clear selection is still missing, see below.

![image](https://user-images.githubusercontent.com/3840267/115863512-38a1fd80-a43e-11eb-9cee-702c34d41659.png)

**Comment by wanjohikibui** [comment]
The clear button appears when there's a selection on the map. It works well

**Comment by gkahiu** [comment]
Cannot confirm as link to spatial entities not working

**Comment by wanjohikibui** [comment]
This is working perfectly now.
