### ISSUE TITLE
Make entity name the default file name when exporting data - UX

### ISSUE THREAD

**Issue by pgathogo** [gltn/stdm-web#15]
It would be nice to default the file name to the entity name that is been exported.

![image](https://user-images.githubusercontent.com/155431/125064935-da3e0000-e0b9-11eb-8401-a4cd833b727f.png)

![image](https://user-images.githubusercontent.com/155431/125064989-eaee7600-e0b9-11eb-836a-be6e0412cd8f.png)

**Comment by wanjohikibui** [comment]
This has been sorted. The default export file name is as follows; <Entity_Name>_Expoert_<todays' dat>.pdf

**Comment by pgathogo** [comment]
This enhancement is done.
