### ISSUE TITLE
Exported PDF file is clipped on the right-hand side

### ISSUE THREAD

**Issue by pgathogo** [gltn/stdm-web#16]
When you export entity data as PDF, the generated document is clipped on the right-hand side.

![image](https://user-images.githubusercontent.com/155431/125065243-44ef3b80-e0ba-11eb-96c9-878cf3279fe5.png)

**Comment by wanjohikibui** [comment]
The issue has been resolved. Depending on the size of the table columns, the generated pdf is exported in landscape orientation.
![farmers](https://user-images.githubusercontent.com/4972951/161278882-1d6ba0a9-1bae-4aa6-a2ab-8b6e18b5764c.png)

**Comment by gkahiu** [comment]
@pgathogo kindly check and close if fixed

**Comment by pgathogo** [comment]
This issue is fixed. However, I have noted the PDF exported adds an extra column that is not visible on the grid.

Note:
Exported CSV and Excel are okay.

Grid:

![image](https://user-images.githubusercontent.com/155431/185210043-ec8fdf0a-8ef3-4091-afcd-b7e4fdac4436.png)

PDF:

![image](https://user-images.githubusercontent.com/155431/185210115-c917b246-defb-49dd-9c0a-ee12c0d85fa9.png)

**Comment by wanjohikibui** [comment]
I have resolved this issue.
![removedetra](https://user-images.githubusercontent.com/4972951/185305505-24d6300b-8222-4814-88c9-c2f38f9c6dcd.png)
