### ISSUE TITLE
Show Map on Clicking Spatial Record

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm-web#20]
Is it possible to show/highlight the map on clicking a spatial record? Also related to issue #17 

![image](https://user-images.githubusercontent.com/3840267/159217179-9c83eeef-1420-4572-a8c9-4655ea05ac9b.png)

**Comment by wanjohikibui** [comment]
Added a section to display individual location of geometry as shown;
![location](https://user-images.githubusercontent.com/4972951/166911753-ef2d02b5-cd78-4c14-bed6-0685b43ef1ab.png)
