### ISSUE TITLE
Some Entity Records Not Loading

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm-web#21]
No records loading for entities highlighted below:

![image](https://user-images.githubusercontent.com/3840267/159217843-e143a0f9-8f0c-48d7-900e-296d7425e420.png)

**Comment by gkahiu** [comment]
OK, let me know once there is a fix or even a user-friendly notification. Will leave this open for now.

**Comment by gkahiu** [comment]
Still not working. 

Also hide detailed error and show a generic message then log this in the backend for troubleshooting.
![image](https://user-images.githubusercontent.com/3840267/167691203-862e3cec-9af0-4998-a3d9-cca1a0de7c41.png)

**Comment by wanjohikibui** [comment]
A generic message has been added to this component as shown below
![Screenshot from 2022-08-08 18-08-55](https://user-images.githubusercontent.com/4972951/183826109-35afb354-0d6b-4dd6-ba42-ae0aae80fcbe.png)
;

**Comment by gkahiu** [comment]
In the settings module for the administrator, is there a way an administrator can be notified that there are such issues? I.e. to make  it more active so that on login a notification can be shown to alert the administrator?

**Comment by wanjohikibui** [comment]
Have added a component in the admin to log all errors experienced in the entities on the front-en
![entity_error](https://user-images.githubusercontent.com/4972951/184319050-bb7e808c-9f1b-46fb-b11e-bb3c7661a155.png)
d

**Comment by gkahiu** [comment]
![image](https://user-images.githubusercontent.com/3840267/184639461-c9063dcb-24d8-40e6-896e-3f98c95bdb29.png)

Two proposals:
1. The text 'Select entity error to change' should be modified since the error log is view only and the logs are generated automatically by the system hence would suggest you revise this (text) accordingly;
2. Related to 1. above, the admin should not add an error log hence am assuming the button 'Add Entity Error' is invalid. Please confirm.
