### ISSUE TITLE
Re-arrange Export/Download Buttons in the Map View

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm-web#22]
- Remove Export to Excel and Export to CSV buttons
- Have a single button for exporting to GeoJSON then submenu for selected and all features
- Ensure consistency of button names

**Comment by wanjohikibui** [comment]
All downloads are on a dropdown menu - Selected and All features

**Comment by gkahiu** [comment]
Kindly include screenshots.

**Comment by wanjohikibui** [comment]
The export button looks as follows;
![export button](https://user-images.githubusercontent.com/4972951/166913345-3bef9d3b-4b9c-4c31-b1bc-432f21ce925c.png)

**Comment by gkahiu** [comment]
Cannot test due to issue #29
