### ISSUE TITLE
Hide Sidebar Not Working

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm-web#28]
![image](https://user-images.githubusercontent.com/3840267/167688768-24a05b43-71bc-4377-8b95-5d7542116822.png)

Clicking on the sidebar hide/show button does not hide the sidebar but attempts to expand the main section to the left.

**Comment by wanjohikibui** [comment]
![components](https://user-images.githubusercontent.com/4972951/183449931-3adaeb51-00f4-40a9-99ac-2de9a12b43a0.png)
The issue has been sorted

**Comment by gkahiu** [comment]
![Sidebar](https://user-images.githubusercontent.com/3840267/184175806-83409e94-b993-4a8b-b35c-a742a86ba8c7.png)

Two issues here:
1. The position of the STDM logo is too much on the right and seems like it is touching the right border, kindly adjust this so that its position is more distributed horizontally;
2. I still see cut off text for the entity names. Am assuming that these should not be showing. My suggestion would be you show a tooltip for the specific entity only when the user hovers over the corresponding icon.

**Comment by wanjohikibui** [comment]
I have sorted out this. On collapsing, the entire logo is visible, with no cut-off words and implemented a hover on the icons
![entitiestihhover](https://user-images.githubusercontent.com/4972951/184306685-d7b8831a-7306-4397-be9d-c7afcb41a042.png)

**Comment by gkahiu** [comment]
Can we hide the UN-Habitat and GLTN logo on collapsing the sidebar? Currently they are too small to see hence it will be better to hide.

**Comment by wanjohikibui** [comment]
This has been done.
![hideengltn](https://user-images.githubusercontent.com/4972951/184674512-e3b86ac7-f7bf-4247-bd14-73c6881ea578.png)
