### ISSUE TITLE
Guarantee Order of Entities After Switching Profiles

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm-web#3]
When switching from `KOPGT` profile to `Rural_Agriculture` then back to `KOPGT`, some of the entities do not appear in the original order. See `Farmer` example below:
1. Before switching profile
![image](https://user-images.githubusercontent.com/3840267/108086962-fc41d200-7087-11eb-9e56-0de7fdbe2da5.png)

2. After switching back to KOPGT profile
![image](https://user-images.githubusercontent.com/3840267/108087041-167bb000-7088-11eb-8a76-6647d69780c5.png)

**Comment by wanjohikibui** [comment]
The issue has been sorted. The entities are in the same order when switching between profiles

**Comment by gkahiu** [comment]
Confirmed, thanks
