### ISSUE TITLE
Issues on Switching Profile

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm-web#31]
When I switch from **KOPGT** to **Rural_Agriculture** profile, I notice the following issues:

1. The farmer records are not loading

![image](https://user-images.githubusercontent.com/3840267/167693680-86c2e0db-e54f-4cd7-a54f-616dd3082c98.png)

2. When I click on the Dashboard in the sidebar, it takes me back to the KOPGT dashboard. I would expect it shows the current profile's (i.e. **Rural_Agriculture**) dashboard

**Comment by wanjohikibui** [comment]
All is sorted. Switching the profile changes the entities in the specific profile

**Comment by gkahiu** [comment]
When I switch the profile from KOPGT to Belaka then I click the Dashboard button, it shows the dashboard for KOPGT and not for Belaka. I would expect it shows the Belaka dashboard.

**Comment by wanjohikibui** [comment]
This issue has been sorted out now and works as should.
