### ISSUE TITLE
Export Data for Spatial Entities to GIS Format

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm-web#5]
Is it possible to export data for spatial entities in GIS format such as Shapefile, GeoJSON etc.?

**Comment by gkahiu** [comment]
Cannot confirm as links to spatial entities are not working.

**Comment by gkahiu** [comment]
Kindly also have a look at this feature enhancement.

**Comment by wanjohikibui** [comment]
This functionality has been added. There are two data export buttons; The one at the top exports all features on the map while the one below exports only the filtered data in the table. The export format available is GeoJSON
![exports](https://user-images.githubusercontent.com/4972951/162729419-0b372728-6755-4032-a843-1fe68304c3d7.png)
.
