### ISSUE TITLE
Uniform Height of Alternating Rows in the Attribute Table

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm-web#6]
Can we adjust the row height to be uniform as they appear to be different? See illustration of height difference below.

![image](https://user-images.githubusercontent.com/3840267/108089342-8b4fe980-708a-11eb-9f8d-1cb6384424d6.png)

**Comment by wanjohikibui** [comment]
Sorted
![image](https://user-images.githubusercontent.com/4972951/109140048-42282580-776d-11eb-89bc-a9453f46fc1a.png)
