### ISSUE TITLE
Colour Styling Consistency of Buttons

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm-web#8]
Can we choose a uniform color scheme for the buttons? For instance, the one for choosing the graph type in the dashboard has a black-grey then as shown below:

![image](https://user-images.githubusercontent.com/3840267/108090338-8ccde180-708b-11eb-90d5-d0a4845455ab.png)

Whereas, the one for choosing the lookup type summary is blue-white:
![image](https://user-images.githubusercontent.com/3840267/108090524-bedf4380-708b-11eb-92c1-dc6571370a28.png)

It will be good to ensure a consistent look and feel for the different UI elements.

**Comment by wanjohikibui** [comment]
This has been sorted
![image](https://user-images.githubusercontent.com/4972951/109139357-7c44f780-776c-11eb-9e90-233219e2f3a5.png)

**Comment by gkahiu** [comment]
Looks better but there is still what appears to be a dark shadow:
![image](https://user-images.githubusercontent.com/3840267/115864567-b1ee2000-a43f-11eb-8476-e9463ef4acfc.png)

Which is not present in other buttons:
![image](https://user-images.githubusercontent.com/3840267/115864635-cfbb8500-a43f-11eb-84f9-f6a6b4ddd38c.png)
