### ISSUE TITLE
Values for Lookup and Foreign Key Columns in Map Popup Window

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm-web#9]
Lookup and foreign key columns need to contain the corresponding display values in the map popup window.

![image](https://user-images.githubusercontent.com/3840267/108091002-4f1d8880-708c-11eb-9f1c-d7da14a90c23.png)

**Comment by wanjohikibui** [comment]
This issue has been resolved
![image](https://user-images.githubusercontent.com/4972951/109137029-ced0e480-7769-11eb-89f8-d62cdf10a20a.png)

**Comment by gkahiu** [comment]
The lookups are fine now, can you remove/hide the **Id** column?

![image](https://user-images.githubusercontent.com/3840267/115864221-4015d680-a43f-11eb-9a91-6267cdc839c8.png)
